#!/usr/bin/env python

# Script that configures some things (such as version) before building .deb package.
#
# Arguments help:
#     1st - working directory
#     2nd - build's version
#     3rd - package's version

import os
import sys

import header_file_parser

# Getting working directory and getting folder with name "DEBIAN"
debianFolder = sys.argv[1]
# If directory exists, starting configuring, otherwise - printing error message
if os.path.exists(debianFolder):
    # Iterating each file in directory
    for filename in os.listdir(debianFolder):
        # If file is file and its name is "control" - we must configure this file
        if os.path.isfile(os.path.join(debianFolder, filename)) and filename == "control":
            # Parsing content of file
            f = open(os.path.join(debianFolder, filename), 'r')
            contentPairs = header_file_parser.parse_pairs(f.read())
            f.close()

            # Configuring version, read from file "build-info/.build_version"
            # Note: element "Version" will always be in file content, it is must-have
            contentPairs["Version"] = sys.argv[2].split(' ')[0] + sys.argv[3]

            # Dumping result to file
            f = open(os.path.join(debianFolder, filename), 'w')
            fileData = ""
            for key in contentPairs:
                fileData += key + ": " + contentPairs[key] + '\n'
            f.write(fileData)
            f.close()

else:
    print "No folder/directory/catalogue \"DEBIAN\" in working folder/directory/catalogue!"
    exit(1)
